#logging:
#  pattern:
#    console: "%d - %msg%n"
#  level: trace
#  file: h://sell.log


#jpa
#  spring:
#    datasource:
#      driver-class-name: com.mysql.jdbc.Driver
#      username: root
#      password: Aa123654
#      url: jdbc:mysql://localhost:3306/sell?characterEncoding=UTF-8&amp;useSSL=false
#    jpa:
#      show-sql: true



#mybatis
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: Aa123654
#    url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8&amp;useSSL=false
#    type: com.alibaba.druid.pool.DruidDataSource
#    initialize: true
#mybatis:
#  type-aliases-package:
#  mapper-locations: classpath:mybatis/*.xml



#mybatis多数据源配置

job:
  ip: 127.0.0.1
  port: 9001
  appName: sell
  appSecret: sakdjasdjkas
  redirectUrl: www.baidu.com
  magic:
   intKey: 8888
   longKey: 12.1
   atcKey: 10
   boolKey: true
spring:
  datasource:
#    sell:
#      driver-class-name: com.mysql.jdbc.Driver
#      username: root
#      password: Aa123654
#      url: jdbc:mysql://localhost:3306/sell?characterEncoding=UTF-8&amp;useSSL=false
#      type: com.alibaba.druid.pool.DruidDataSource
#    mall:
#      driver-class-name: com.mysql.jdbc.Driver
#      username: root
#      password: Aa123654
#      url: jdbc:mysql://localhost:3306/mmall?characterEncoding=UTF-8&amp;useSSL=false
#      type: com.alibaba.druid.pool.DruidDataSource
    flybird:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql://192.168.79.131:3306/flybird?characterEncoding=UTF-8&amp;useSSL=false
      type: com.alibaba.druid.pool.DruidDataSource
  freemarker:
    allow-request-override: false
    cache: true
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
  rabbitmq:
    host: 192.168.79.136
    port: 5672
    username: guest
    password: guest
    connection-timeout: 15000
    listener:
      acknowledge-mode: manual
      prefetch: 10
rocketmq:
  producer:
    groupName: sell
    namesrvAddr: 192.168.79.137:9876
    sendMsgTimeout: 3000
    maxMessageSize: 40960
  consumer:
    groupName: sell
    namesrvAddr: 192.168.79.137:9876
    topic: demoTopic
    tag: demoTag
    consumeThreadMax: 10
    consumeThreadMin: 2
