#logging:
#  pattern:
#    console: "%d - %msg%n"
#  level: trace
#  file: h://sell.log


#jpa
#  spring:
#    datasource:
#      driver-class-name: com.mysql.jdbc.Driver
#      username: root
#      password: Aa123654
#      url: jdbc:mysql://localhost:3306/sell?characterEncoding=UTF-8&amp;useSSL=false
#    jpa:
#      show-sql: true



#mybatis
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: Aa123654
#    url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8&amp;useSSL=false
#    type: com.alibaba.druid.pool.DruidDataSource
#    initialize: true
#mybatis:
#  type-aliases-package:
#  mapper-locations: classpath:mybatis/*.xml



#mybatis多数据源配置

job:
  ip: 1270.0.01
  port: 9001
  appName: sell
  appSecret: sakdjasdjkas
  redirectUrl: www.baidu.com
  magic:
   intKey: 8888
   longKey: 12.1
   atcKey: 10
   boolKey: true
spring:
  datasource:
    sell:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: Aa123654
      url: jdbc:mysql://localhost:3306/sell?characterEncoding=UTF-8&amp;useSSL=false
      type: com.alibaba.druid.pool.DruidDataSource
    mall:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: Aa123654
      url: jdbc:mysql://localhost:3306/mmall?characterEncoding=UTF-8&amp;useSSL=false
      type: com.alibaba.druid.pool.DruidDataSource
  freemarker:
    allow-request-override: false
    cache: true
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false

rocketmq:
  producer:
    # 发送同一类消息的设置为同一个group，保证唯一,默认不需要设置，rocketmq会使用ip@pid(pid代表jvm名字)作为唯一标示
    groupName: vehicleProducerGroup
    #mq的nameserver地址
    namesrvAddr: 192.168.79.128:9876
    #如果需要同一个jvm中不同的producer往不同的mq集群发送消息，需要设置不同的instanceName
    instanceName: vehicleProducer
    #topic名称
    topic: TEST
    #根据实际情况设置消息的tag
    tag: TEST
    #消息最大长度
    maxMessageSize: 131072 # 1024*128
    #发送消息超时时间
    sendMsgTimeout: 10000
  consumer:
    namesrvAddr: 192.168.79.128:9876
    groupName: vehicleProducerGroup
    topic: sms
    tag: verifycode
    consumeThreadMin: 20
    consumeThreadMax: 64